// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package githubapi

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// Varying levels of contributions from none to many.
type ContributionLevel string

const (
	// Lowest 25% of days of contributions.
	ContributionLevelFirstQuartile ContributionLevel = "FIRST_QUARTILE"
	// Highest 25% of days of contributions. More contributions than the third quartile.
	ContributionLevelFourthQuartile ContributionLevel = "FOURTH_QUARTILE"
	// No contributions occurred.
	ContributionLevelNone ContributionLevel = "NONE"
	// Second lowest 25% of days of contributions. More contributions than the first quartile.
	ContributionLevelSecondQuartile ContributionLevel = "SECOND_QUARTILE"
	// Second highest 25% of days of contributions. More contributions than second quartile, less than the fourth quartile.
	ContributionLevelThirdQuartile ContributionLevel = "THIRD_QUARTILE"
)

var AllContributionLevel = []ContributionLevel{
	ContributionLevelFirstQuartile,
	ContributionLevelFourthQuartile,
	ContributionLevelNone,
	ContributionLevelSecondQuartile,
	ContributionLevelThirdQuartile,
}

// GetContributionCalendarResponse is returned by GetContributionCalendar on success.
type GetContributionCalendarResponse struct {
	// Lookup a user by login.
	User GetContributionCalendarUser `json:"user"`
}

// GetUser returns GetContributionCalendarResponse.User, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarResponse) GetUser() GetContributionCalendarUser { return v.User }

// GetContributionCalendarUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type GetContributionCalendarUser struct {
	// The username used to login.
	Login string `json:"login"`
	// The user's public profile name.
	Name string `json:"name"`
	// The user's public profile bio.
	Bio string `json:"bio"`
	// The HTTP URL for this user
	Url string `json:"url"`
	// A list of users the given user is followed by.
	Followers GetContributionCalendarUserFollowersFollowerConnection `json:"followers"`
	// A list of users the given user is following.
	Following GetContributionCalendarUserFollowingFollowingConnection `json:"following"`
	// The collection of contributions this user has made to different repositories.
	ContributionsCollection GetContributionCalendarUserContributionsCollection `json:"contributionsCollection"`
}

// GetLogin returns GetContributionCalendarUser.Login, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUser) GetLogin() string { return v.Login }

// GetName returns GetContributionCalendarUser.Name, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUser) GetName() string { return v.Name }

// GetBio returns GetContributionCalendarUser.Bio, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUser) GetBio() string { return v.Bio }

// GetUrl returns GetContributionCalendarUser.Url, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUser) GetUrl() string { return v.Url }

// GetFollowers returns GetContributionCalendarUser.Followers, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUser) GetFollowers() GetContributionCalendarUserFollowersFollowerConnection {
	return v.Followers
}

// GetFollowing returns GetContributionCalendarUser.Following, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUser) GetFollowing() GetContributionCalendarUserFollowingFollowingConnection {
	return v.Following
}

// GetContributionsCollection returns GetContributionCalendarUser.ContributionsCollection, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUser) GetContributionsCollection() GetContributionCalendarUserContributionsCollection {
	return v.ContributionsCollection
}

// GetContributionCalendarUserContributionsCollection includes the requested fields of the GraphQL type ContributionsCollection.
// The GraphQL type's documentation follows.
//
// A collection of contributions made by a user, including opened issues, commits, and pull requests.
// Contributions in private and internal repositories are only included with the optional read:user scope.
type GetContributionCalendarUserContributionsCollection struct {
	// The years the user has been making contributions with the most recent year first.
	ContributionYears []int `json:"contributionYears"`
	// The beginning date and time of this collection.
	StartedAt string `json:"startedAt"`
	// The ending date and time of this collection.
	EndedAt string `json:"endedAt"`
	// Determine if there are any contributions in this collection.
	HasAnyContributions bool `json:"hasAnyContributions"`
	// A calendar of this user's contributions on GitHub.
	ContributionCalendar GetContributionCalendarUserContributionsCollectionContributionCalendar `json:"contributionCalendar"`
}

// GetContributionYears returns GetContributionCalendarUserContributionsCollection.ContributionYears, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollection) GetContributionYears() []int {
	return v.ContributionYears
}

// GetStartedAt returns GetContributionCalendarUserContributionsCollection.StartedAt, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollection) GetStartedAt() string {
	return v.StartedAt
}

// GetEndedAt returns GetContributionCalendarUserContributionsCollection.EndedAt, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollection) GetEndedAt() string { return v.EndedAt }

// GetHasAnyContributions returns GetContributionCalendarUserContributionsCollection.HasAnyContributions, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollection) GetHasAnyContributions() bool {
	return v.HasAnyContributions
}

// GetContributionCalendar returns GetContributionCalendarUserContributionsCollection.ContributionCalendar, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollection) GetContributionCalendar() GetContributionCalendarUserContributionsCollectionContributionCalendar {
	return v.ContributionCalendar
}

// GetContributionCalendarUserContributionsCollectionContributionCalendar includes the requested fields of the GraphQL type ContributionCalendar.
// The GraphQL type's documentation follows.
//
// A calendar of contributions made on GitHub by a user.
type GetContributionCalendarUserContributionsCollectionContributionCalendar struct {
	// A list of hex color codes used in this calendar. The darker the color, the more contributions it represents.
	Colors []string `json:"colors"`
	// Determine if the color set was chosen because it's currently Halloween.
	IsHalloween bool `json:"isHalloween"`
	// A list of the months of contributions in this calendar.
	Months []GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth `json:"months"`
	// The count of total contributions in the calendar.
	TotalContributions int `json:"totalContributions"`
	// A list of the weeks of contributions in this calendar.
	Weeks []GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek `json:"weeks"`
}

// GetColors returns GetContributionCalendarUserContributionsCollectionContributionCalendar.Colors, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendar) GetColors() []string {
	return v.Colors
}

// GetIsHalloween returns GetContributionCalendarUserContributionsCollectionContributionCalendar.IsHalloween, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendar) GetIsHalloween() bool {
	return v.IsHalloween
}

// GetMonths returns GetContributionCalendarUserContributionsCollectionContributionCalendar.Months, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendar) GetMonths() []GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth {
	return v.Months
}

// GetTotalContributions returns GetContributionCalendarUserContributionsCollectionContributionCalendar.TotalContributions, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendar) GetTotalContributions() int {
	return v.TotalContributions
}

// GetWeeks returns GetContributionCalendarUserContributionsCollectionContributionCalendar.Weeks, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendar) GetWeeks() []GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek {
	return v.Weeks
}

// GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth includes the requested fields of the GraphQL type ContributionCalendarMonth.
// The GraphQL type's documentation follows.
//
// A month of contributions in a user's contribution graph.
type GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth struct {
	// The date of the first day of this month.
	FirstDay string `json:"firstDay"`
	// The name of the month.
	Name string `json:"name"`
	// How many weeks started in this month.
	TotalWeeks int `json:"totalWeeks"`
	// The year the month occurred in.
	Year int `json:"year"`
}

// GetFirstDay returns GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth.FirstDay, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth) GetFirstDay() string {
	return v.FirstDay
}

// GetName returns GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth.Name, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth) GetName() string {
	return v.Name
}

// GetTotalWeeks returns GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth.TotalWeeks, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth) GetTotalWeeks() int {
	return v.TotalWeeks
}

// GetYear returns GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth.Year, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendarMonthsContributionCalendarMonth) GetYear() int {
	return v.Year
}

// GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek includes the requested fields of the GraphQL type ContributionCalendarWeek.
// The GraphQL type's documentation follows.
//
// A week of contributions in a user's contribution graph.
type GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek struct {
	// The date of the earliest square in this week.
	FirstDay string `json:"firstDay"`
	// The days of contributions in this week.
	ContributionDays []GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay `json:"contributionDays"`
}

// GetFirstDay returns GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek.FirstDay, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek) GetFirstDay() string {
	return v.FirstDay
}

// GetContributionDays returns GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek.ContributionDays, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek) GetContributionDays() []GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay {
	return v.ContributionDays
}

// GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay includes the requested fields of the GraphQL type ContributionCalendarDay.
// The GraphQL type's documentation follows.
//
// Represents a single day of contributions on GitHub by a user.
type GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay struct {
	// The hex color code that represents how many contributions were made on this day compared to others in the calendar.
	Color string `json:"color"`
	// How many contributions were made by the user on this day.
	ContributionCount int `json:"contributionCount"`
	// Indication of contributions, relative to other days. Can be used to indicate
	// which color to represent this day on a calendar.
	ContributionLevel ContributionLevel `json:"contributionLevel"`
	// The day this square represents.
	Date string `json:"date"`
	// A number representing which day of the week this square represents, e.g., 1 is Monday.
	Weekday int `json:"weekday"`
}

// GetColor returns GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay.Color, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay) GetColor() string {
	return v.Color
}

// GetContributionCount returns GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay.ContributionCount, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay) GetContributionCount() int {
	return v.ContributionCount
}

// GetContributionLevel returns GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay.ContributionLevel, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay) GetContributionLevel() ContributionLevel {
	return v.ContributionLevel
}

// GetDate returns GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay.Date, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay) GetDate() string {
	return v.Date
}

// GetWeekday returns GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay.Weekday, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay) GetWeekday() int {
	return v.Weekday
}

// GetContributionCalendarUserFollowersFollowerConnection includes the requested fields of the GraphQL type FollowerConnection.
// The GraphQL type's documentation follows.
//
// The connection type for User.
type GetContributionCalendarUserFollowersFollowerConnection struct {
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// GetTotalCount returns GetContributionCalendarUserFollowersFollowerConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserFollowersFollowerConnection) GetTotalCount() int {
	return v.TotalCount
}

// GetContributionCalendarUserFollowingFollowingConnection includes the requested fields of the GraphQL type FollowingConnection.
// The GraphQL type's documentation follows.
//
// The connection type for User.
type GetContributionCalendarUserFollowingFollowingConnection struct {
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// GetTotalCount returns GetContributionCalendarUserFollowingFollowingConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *GetContributionCalendarUserFollowingFollowingConnection) GetTotalCount() int {
	return v.TotalCount
}

// __GetContributionCalendarInput is used internally by genqlient
type __GetContributionCalendarInput struct {
	Login string `json:"login"`
	From  string `json:"from"`
	To    string `json:"to"`
}

// GetLogin returns __GetContributionCalendarInput.Login, and is useful for accessing the field via an interface.
func (v *__GetContributionCalendarInput) GetLogin() string { return v.Login }

// GetFrom returns __GetContributionCalendarInput.From, and is useful for accessing the field via an interface.
func (v *__GetContributionCalendarInput) GetFrom() string { return v.From }

// GetTo returns __GetContributionCalendarInput.To, and is useful for accessing the field via an interface.
func (v *__GetContributionCalendarInput) GetTo() string { return v.To }

// The query executed by GetContributionCalendar.
const GetContributionCalendar_Operation = `
query GetContributionCalendar ($login: String!, $from: DateTime!, $to: DateTime!) {
	user(login: $login) {
		login
		name
		bio
		url
		followers {
			totalCount
		}
		following {
			totalCount
		}
		contributionsCollection(from: $from, to: $to) {
			contributionYears
			startedAt
			endedAt
			hasAnyContributions
			contributionCalendar {
				colors
				isHalloween
				months {
					firstDay
					name
					totalWeeks
					year
				}
				totalContributions
				weeks {
					firstDay
					contributionDays {
						color
						contributionCount
						contributionLevel
						date
						weekday
					}
				}
			}
		}
	}
}
`

func GetContributionCalendar(
	ctx_ context.Context,
	client_ graphql.Client,
	login string,
	from string,
	to string,
) (data_ *GetContributionCalendarResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetContributionCalendar",
		Query:  GetContributionCalendar_Operation,
		Variables: &__GetContributionCalendarInput{
			Login: login,
			From:  from,
			To:    to,
		},
	}

	data_ = &GetContributionCalendarResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
